-- MySQL Script generated by MySQL Workbench
-- Tue Sep 14 15:43:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `rolUsuario` VARCHAR(45) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC) VISIBLE,
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ListaReproduccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ListaReproduccion` (
  `idListaReproduccion` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `idCancionesLista` INT NULL,
  `fechaUltimReprod` DATE NOT NULL,
  PRIMARY KEY (`idListaReproduccion`),
  UNIQUE INDEX `idCancionesLista_UNIQUE` (`idCancionesLista` ASC) VISIBLE,
  INDEX `UsuarioListaReproduccion_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `UsuarioListaReproduccion`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Artistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Artistas` (
  `idArtistas` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `nacionalidad` VARCHAR(45) NULL,
  PRIMARY KEY (`idArtistas`),
  UNIQUE INDEX `idArtista_UNIQUE` (`idArtistas` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Album` (
  `idAlbum` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `selloDisco` VARCHAR(45) NOT NULL,
  `agno` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAlbum`),
  UNIQUE INDEX `idAlbum_UNIQUE` (`idAlbum` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Genero` (
  `idGenero` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idGenero`),
  UNIQUE INDEX `idGenero_UNIQUE` (`idGenero` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Canciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Canciones` (
  `idCanciones` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `agno` VARCHAR(45) NOT NULL,
  `idArtista` INT NOT NULL,
  `idAlbum` INT NOT NULL,
  `idGenero` INT NOT NULL,
  UNIQUE INDEX `idCancion_UNIQUE` (`idCanciones` ASC) VISIBLE,
  INDEX `idArtistaCancion_idx` (`idArtista` ASC) VISIBLE,
  PRIMARY KEY (`idCanciones`),
  INDEX `idAlbumIdCancion_idx` (`idAlbum` ASC) VISIBLE,
  INDEX `idGenero_idx` (`idGenero` ASC) VISIBLE,
  CONSTRAINT `idArtistaCancion`
    FOREIGN KEY (`idArtista`)
    REFERENCES `mydb`.`Artistas` (`idArtistas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idAlbumIdCancion`
    FOREIGN KEY (`idAlbum`)
    REFERENCES `mydb`.`Album` (`idAlbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idGenero`
    FOREIGN KEY (`idGenero`)
    REFERENCES `mydb`.`Genero` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ListaGuardada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ListaGuardada` (
  `idListaGuardada` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idListaGuardada`),
  UNIQUE INDEX `idListaGuardada_UNIQUE` (`idListaGuardada` ASC) VISIBLE,
  INDEX `idListaGuardadaidUsuario_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `idListaGuardadaidUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CancionesLista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CancionesLista` (
  `idCancionesLista` INT NOT NULL AUTO_INCREMENT,
  `idListaReprod` INT NOT NULL,
  `idCancion` INT NOT NULL,
  `favoritaCancion` TINYINT NULL,
  PRIMARY KEY (`idCancionesLista`),
  UNIQUE INDEX `idCancionesLista_UNIQUE` (`idCancionesLista` ASC) VISIBLE,
  INDEX `CancionCancionLista_idx` (`idCancion` ASC) VISIBLE,
  INDEX `idListaReprodCancionLista_idx` (`idListaReprod` ASC) VISIBLE,
  CONSTRAINT `idCancionCancionLista`
    FOREIGN KEY (`idCancion`)
    REFERENCES `mydb`.`Canciones` (`idCanciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idListaReprodCancionLista`
    FOREIGN KEY (`idListaReprod`)
    REFERENCES `mydb`.`ListaReproduccion` (`idListaReproduccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idListaGuardadaCancionLista`
    FOREIGN KEY (`idListaReprod`)
    REFERENCES `mydb`.`ListaGuardada` (`idListaGuardada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
